name: Docker build

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths: ['frontend/**']

jobs:
    plan:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout code
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up docker buildx
              uses: docker/setup-buildx-action@v3
              
            
            - name: Login to docker registry
              uses: docker/login-action@v3
              with:
                registry: ${{ secrets.DOCKER_REGISTRY }}
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Change dir to frontend
              run: cd frontend

            - name: Build and push portfolio Docker image
              uses: docker/build-push-action@v6
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                platforms: linux/amd64
                push: true
                tags: dagmarl/portfolio:latest
              
