name: Redeploy

on:
    workflow_dispatch:
env:
  ec2_output: $(terraform output ec2id)
jobs:
    redeploy:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with: 
                terraform_wrapper: false

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.2.1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: 'us-east-1'

            - name: Add file to ec2
              run: |
                  cd terraform
                  terraform fmt
                  terraform init
                  aws ssm send-command \
                  --document-name "AWS-RunShellScript" \
                  --comment "Redeploy Nextjs app" \
                  --instance-ids ${{ env.ec2_output }} \
                  --region "us-east-1" \
                  --parameters commands="\" 
                  sudo su - ubuntu -c 'touch myfiles'
                  \"" \


