name: Terrafrom

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths: ['terraform/**']

jobs:
    plan:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout code
              uses: actions/checkout@v4

            # Installs Terraform on GitHub runner
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            # Configures your AWS access by using the credentials stored in GitHub Secrets
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${ { secrets.AWS_ACCESS_KEY_ID } }
                  aws-secret-access-key: ${ { secrets.AWS_SECRET_ACCESS_KEY } }
                  aws-region: "us-east-1"

            # Initialize terraform
            - name: Initialize Terraform
              run: terraform init

            # Execute the terraform plan
            - name: Terraform Plan
              run: terraform plan

