name: Terrafrom Apply

on:
    workflow_dispatch:

jobs:
    plan:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.2.1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: 'us-east-1'

            - name: Initialize Terraform
              run: |
                  cd terraform
                  terraform fmt
                  terraform init

            - name: Terraform Plan
              run: |
                  cd terraform
                  terraform fmt
                  terraform plan

            - name: Terraform Apply
              run: |
                  cd terraform
                  terraform fmt
                  terraform apply -auto-approve
